### ISSUE TITLE
[1.12.2] Interference with squid spawning

### ISSUE THREAD

**Issue by faeldray** [OrderedChaos-Dev/ProjectVibrantJourneys#84]
**Describe the bug**
Squids do spawn when you first comes across an ocean (in like a 10 chunk radius) but if you head further out in the ocean, you'll never see another one again. Changing the value of `restrictSquidsToOceans` doesn't seem to affect this.

Tested with:
Forge 2847
P:VJ 1.6.4
Nature's Compass 1.5.1 (just so I could find oceans easily)

**Comment by OrderedChaos-Dev** [comment]
The 1.12 version is no longer being developed in favor of the 1.15.1 version

**Comment by Norfried** [comment]
If you are a 1.12.2 user reading this, one solution to this issue is as follows.

Set the spawn weight of regular starfish spawns to 0, and the squids shall return.
I hope you're not attached to the sea stars, but hear me out.
They will absolutely overcrowd the ocean and keep other aquatic mobs from spawning if they're not disabled.
You have been informed.

That tis all! :)
